mex -largeArrayDims CBCD_size1_gc.cpp
mex -largeArrayDims CBCD_size2_gc.cpp
mex -largeArrayDims CBCD_size3_gc.cpp
mex -largeArrayDims RBCD_size1_gc.cpp
mex -largeArrayDims RBCD_size1_gc.cpp
mex -largeArrayDims RBCD_size3_gc.cpp
mex -largeArrayDims CBCD_size1_fx.cpp
mex -largeArrayDims CBCD_size2_fx.cpp
mex -largeArrayDims CBCD_size3_fx.cpp
mex -largeArrayDims RBCD_size3_gc_h.cpp
mex -largeArrayDims RBCD_size2_gc_h.cpp
mex -largeArrayDims RBCD_size3_gc_u.cpp
mex -largeArrayDims RBCD_size2_gc_u.cpp
mex -largeArrayDims RBCD_size1_gc_u.cpp
mex -largeArrayDims RBCD3.cpp
mex -largeArrayDims RBCD2.cpp